config/routes.rb
Tweeter::Application.routes.draw do

  resources :users, :only => [:update, :create, :destroy] do
    resources :tweets do
      member do
        put :vote
      end
    end
  end
  get '/newest' => 'users#newest', :as => :newest
  get '/new' => 'users#new', :as => :new_user
  get '/:username' => 'users#show', :as => :user
  root :to => 'users#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :load_user
  before_filter :load_tweet, :except => [:create, :new]

  def edit
  end

  def vote
    session[:voted_on] ||= []
    unless session[:voted_on].include?(@tweet.id)
      @tweet.vote_count += 1
      @tweet.save
      session[:voted_on] << @tweet.id
    end
    redirect_to user_path(@user.username)
  end

  def create
    @tweet = @user.tweets.create params[:tweet]
    redirect_to user_path(@user.username)
  end

  def update
    @tweet.update_attributes params[:tweet]
    redirect_to user_path(@user.username)
  end

  def destroy
    @tweet.destroy
    redirect_to user_path(@user.username)
  end


  private

  def load_user
    @user = User.find(params[:user_id])
  end

  def load_tweet
    @tweet = @user.tweets.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def newest
    @users = User.order('created_at desc')
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by_username(params[:username])
    render :action => :not_found unless @user
  end

  def create
    @user = User.create(params[:user])
    redirect_to user_path(@user.username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweeter</title>
  <%= stylesheet_link_tag    "http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/tweets/edit.html.erb
<%= form_for [@user, @tweet] do |f| %>
  <%= f.text_field :content %>
  <%= submit_tag 'Save' %>
<% end %>

app/views/users/index.html.erb
<h1>All Users (<%= @users.count %>)</h1>
<h3>
  Maybe you want to see the <%= link_to 'newest users', newest_path %>?
</h3>
<h3>
  <%= link_to 'Sign up', new_user_path %>
</h3>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_path(user.username) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create new user</h1>

<%= form_for @user do |f| %>
  <label>Username</label>
  <%= f.text_field :username %>

  <label>Location</label>
  <%= f.text_field :location %>

  <label>Birthday</label>
  <%= f.date_select :birthdate %>

  <label>Bio</label>
  <%= f.text_area :bio %>

  <%= submit_tag 'Save', :class => 'btn primary large' %>
<% end %>

app/views/users/newest.html.erb
<h1>New Users (<%= @users.count %>)</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_path(user.username) %></li>
  <% end %>
</ul>

app/views/users/not_found.html.erb
<h1>User <%= params[:username] %> not found</h1>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h2><%= @user.location %></h2>

<p><%= @user.bio %></p>

<%= form_for [@user, Tweet.new] do |f| %>
  <%= f.text_field :content %>
  <%= submit_tag 'Post' %>
<% end %>

<table>
  <% @user.tweets.each do |tweet| %>
    <tr>
      <td><%= tweet.content %></td>
      <td>
        <%= tweet.vote_count %> 
        <%= button_to '+', vote_user_tweet_path(@user, tweet), :method => :put %>
      </td>
      <td><%= link_to 'Edit', edit_user_tweet_path(@user, tweet) %></td>
      <td><%= link_to 'Delete', user_tweet_path(@user, tweet), :method => :delete, :confirm => "Are you sure?" %></td>
    </tr>
  <% end %>
</table>